name: solar sailer

# Code
highlighter: pygments
exclude: ['_sources', '_raws']

# Publishing
#future: false
show_drafts: nil

# Permalink format (without day)
permalink: /:categories/:year/:month/:title

# Pagination
paginate_path: 'page-:num'
paginate: 20

# Markdown formatter
markdown: redcarpet
