title: "Solar Sailer"
author: "Matthieu Oger"
description: "A collection of thoughts and opinions by Matthieu Oger"
keywords: "solar, sailer, matthieu, oger, technology, design, development, dev"

github_username:  "solarsailer"
twitter_username: "solarsailer"
dribbble_username: "solarsailer"

google_tracking_code: "UA-41853457-1"

url: "http://solarsailer.net"

# -------------------------------------------------------
# Defaults.
# -------------------------------------------------------

show_drafts: nil

permalink: /:categories/:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# --------------------------------------------------------------
# Markdown.
# --------------------------------------------------------------

markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true

# --------------------------------------------------------------
# Syntax Highlighter.
# --------------------------------------------------------------

highlighter: rouge

# -------------------------------------------------------
# Pagination.
# -------------------------------------------------------

paginate_path: '/page/:num/'
paginate: 20

# --------------------------------------------------------------
# Build Configuration.
# --------------------------------------------------------------

include:
  - '_pages'

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - webpack.config.js
  - node_modules
  - src
  - npm-debug.log

keep_files:
  - static/bundle.css
  - static/bundle.css.map
  - static/bundle.js
  - static/bundle.js.map

# --------------------------------------------------------------
# Plugins.
# --------------------------------------------------------------

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
