name: solar sailer

# Remove folders from build.
exclude: ['_raws', 'README.md']

# Code syntax highlighter.
# TODO: switch to `rouge` when Github Pages supports it.
highlighter: pygments

# -------------------------------------------------------
# Links & pagination.
# -------------------------------------------------------

# Permalink format (without day).
permalink: /:categories/:year/:month/:title/

# Pagination.
paginate_path: 'page-:num'
paginate: 20

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["footnotes", "no_intra_emphasis", "autolink", "strikethrough", "space_after_headers"]

# -------------------------------------------------------
# Sass.
# -------------------------------------------------------

sass:
  style: :compressed

# -------------------------------------------------------
# Plugins.
# -------------------------------------------------------

gems:
  - jekyll-paginate
