name: solar sailer

# -------------------------------------------------------
# Globals.
# -------------------------------------------------------

show_drafts: nil
permalink: /:categories/:year/:month/:title/

exclude: ['_raws', 'README.md']

# -------------------------------------------------------
# Defaults.
# -------------------------------------------------------

# -------------------------------------------------------
# Markdown.
# -------------------------------------------------------

markdown: redcarpet

redcarpet:
  extensions: ["footnotes", "no_intra_emphasis", "autolink", "strikethrough", "space_after_headers"]

# -------------------------------------------------------
# Code.
# -------------------------------------------------------

highlighter: rouge

# -------------------------------------------------------
# Pagination.
# -------------------------------------------------------

paginate_path: 'page-:num'
paginate: 20

# -------------------------------------------------------
# Sass.
# -------------------------------------------------------

sass:
  style: :compressed

# -------------------------------------------------------
# Plugins.
# -------------------------------------------------------

gems:
  - jekyll-paginate
  - jekyll-redirect-from
