# Basic.
baseURL = 'https://matthieuoger.com/'
languageCode = 'en-us'

# Metadata.
title = 'Matthieu Oger'
copyright = '© 2024 **Matthieu Oger**'

[permalinks]
  [permalinks.section]
    posts = '/articles/'
  [permalinks.page]
    posts = '/:year/:month/:filename/'

# Pagination.
[pagination]
  pagerSize = 9

[outputs]
  home = ['html', 'rss']
  page = ['html']
  section = ['html']
  taxonomy = []
  term = []
