import {css} from 'styled-components'

import {sizes} from '../../config'

import hintStyles from './hint'

// -------------------------------------------------------------
// Footnotes.
// -------------------------------------------------------------

export default css`
  a.footnote-ref {
    box-sizing: content-box;
    color: white;
    margin-left: 2px;
    padding-left: 5px;
    padding-right: 5px;
    background: var(--color-accent);
    border: 1px solid transparent;
    border-radius: 3px;
    font-size: 1.2rem;

    &:hover {
      color: var(--color-accent);
      background: hsl(0, 0%, 93%);
      border: 1px solid var(--color-accent);
    }
  }

  /*
    Note: yes, this is dirty, but we don't have any control
    on how footnotes are generated by Remark.
  */
  .footnotes {
    position: relative;

    margin-top: 10rem;
    padding: 2rem 0;

    background: hsl(0, 0%, 93%);
    border-radius: ${sizes.block.radius}px;

    font-size: 0.85em;

    &::before {
      content: 'Footnotes';
      ${hintStyles};
    }

    hr {
      display: none;
    }

    ol {
      margin-bottom: 0;
      padding-left: 0;
      list-style: none;
    }

    li {
      position: relative;
      margin-bottom: 2rem;
      padding: 0 2rem 0;
      border-bottom: 1px solid hsla(0, 0%, 0%, 0.1);

      &:last-of-type {
        margin-bottom: -2rem;
        padding-bottom: 0;
        border: none;
      }

      &:target {
        font-weight: 500;
      }

      blockquote {
        margin-left: 0;
        margin-right: 0;
        padding: 1.5rem;
        background: hsl(0, 0%, 87%);
        border: none;
      }

      .footnote-backref {
        position: absolute;
        top: 0;
        right: -11px;

        margin-left: 2rem;
        padding: 6px 6px 3px;
        background: hsl(var(--hue-accent), 77%, 81%);
        border-bottom: none;
        border-radius: ${sizes.block.radius}px;

        font-size: 0.9em;
        line-height: normal;

        &:hover {
          color: white;
          background: var(--color-accent);
          transform: scale(1.2);
        }
      }
    }
  }
`
